name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [ "*" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build@main
        with:
          target: debug
          platform: ubuntu-latest

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: ./.github/workflows/build@main
        with:
          target: debug
          platform: macos-latest

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: ./.github/workflows/build@main
        with:
          target: debug
          platform: windows-latest
          
