name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  create_release_page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Create release page
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ inputs.version }}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${{ inputs.version }}" \
            --generate-notes

  build-ubuntu:
    needs: create_release_page
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/build
        with:
          profile: release

      - name: Rename file
        run: mv target/release/riscv-harness target/release/riscv-harness-linux

      - name: Upload ubuntu artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/riscv-harness-linux
          tag_name: ${{ inputs.version }}

  build-macos:
    needs: create_release_page
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      
      - name: Build
        uses: ./.github/actions/build
        with:
          profile: release

      - name: Rename file
        run: mv target/release/riscv-harness target/release/riscv-harness-macos

      - name: Upload macOS artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/riscv-harness-macos
          tag_name: ${{ inputs.version }}

  build-windows:
    needs: create_release_page
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/build
        with:
          profile: release

      - name: Rename file
        run: mv target/release/riscv-harness.exe target/release/riscv-harness-win64.exe

      - name: Upload Windows artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/riscv-harness-win64.exe
          tag_name: ${{ inputs.version }}
          
