name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  create_draft_release_page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Create release page
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: true
          release_name: Release ${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          body_path: CHANGELOG.md

  build-ubuntu:
    needs: create_draft_release_page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/build
        with:
          profile: release

      - name: Upload ubuntu artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/riscv-harness
          tag: ${{ inputs.version }}

  build-macos:
    needs: create_draft_release_page
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Build
        uses: ./.github/actions/build
        with:
          profile: release

      - name: Upload macOS artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/riscv-harness
          tag: ${{ inputs.version }}

  build-windows:
    needs: create_draft_release_page
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/build
        with:
          profile: release

      - name: Upload Windows artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/riscv-harness.exe
          tag: ${{ inputs.version }}
          
